from llama_cpp import Llama
from helpers import save_history, HISTORY_CONTAINER, get_current_screen
from Core import chat_prompt_gen, Command_Executer, error_handler
from Tools import Pre_Executor
from STT import STT
from TTS import TTS
import os
import json

models = {
    "8" : {
            "repo" :"Qwen/Qwen2.5-7B-Instruct-GGUF",
            "model" : "qwen2.5-7b-instruct-fp16-00001-of-00004.gguf"
        },
    "6" : {
            "repo" :"Qwen/Qwen2.5-3B-Instruct-GGUF",
            "model" : "qwen2.5-3b-instruct-q6_k.gguf"
        },
    "4" : {
            "repo" : "Qwen/Qwen2.5-3B-Instruct-GGUF",
            "model" : "qwen2.5-3b-instruct-fp16-00001-of-00002.gguf",
        },
    "macro_model" : {
            "repo" : "Qwen/Qwen2.5-1.5B-Instruct-GGUF",
            "model" : "qwen2.5-1.5b-instruct-q5_k_m.gguf",
    }            
}

def decider():
    "Decides which model to Load based on the System Configuration, and Returns the Model Path and Repository Information"
    with open("UserPreferences/UserMetaData.json", "r") as f:
        data = json.load()
    user = data.get("user", {})
    if not user:
        raise ValueError("User information not found in UserMetaData.json, re-execute the install.sh. Don't Worry Nothing gonna download again")
    gpu = user.get("vram", "N/A" )
    if int(gpu) >= 8000:
        return models["8"]
    elif int(gpu) >= 6000:
        return models["6"]
    elif int(gpu) >= 4000:  
        return models["4"]
    else:
        cpu = user.get("total_ram", "N/A")
        if cpu == "Unknown" or cpu == "N/A":
            raise ValueError("CPU information not found in UserMetaData.json, re-execute the install.sh. Don't Worry Nothing gonna download again")
        elif cpu >= 15000:
            return models["8"]
        elif cpu >= 12000:
            return models["6"]
        elif cpu >= 8000:
            return models["4"]
        else:            
            return models["macro_model"]
            

class Sabrina:
    """
Core program to run the application.

Allows loading a language model from either a local path or a Hugging Face repository.

Args:
    llmLocation (str): Path to the local model file
    llm_repo_id (str): Hugging Face repository ID
    llm_filename (str): Model filename in the repository
"""
    def __init__(
        self,
        llmLocation="your/model/model.gguf",
        llm_repo_id="Qwen/Qwen2.5-3B-Instruct-GGUF",
        llm_filename="qwen2.5-3b-instruct-q6_k.gguf",
    ):
        self.agent = self.load_model(llmLocation, llm_repo_id, llm_filename)
        self.stt = STT()
        self.tts = TTS()
        self.noinput = 0

    def load_model(self, path, repo_id, filename):
        n_gpu_layers = -1
        if os.path.isfile(path) and path.endswith(".gguf"):
            return Llama(
                model_path=path,
                n_ctx=8192,
                n_threads=4,
                n_gpu_layers=n_gpu_layers,
                temperature=0.1,
                verbose=False
            )
        else:
            try:
                return Llama.from_pretrained(
                    repo_id=repo_id,
                    filename=filename,
                    n_ctx=8192,
                    n_threads=4,
                    n_gpu_layers=n_gpu_layers,
                    temperature=0.1,
                    verbose=False
                )
            except Exception as e:
                raise RuntimeError(f"Model loading failed: {e}")
    
    def responsed(self, inputData):
        "Creates Response for the User Input"

        if not inputData:
            self.noinput += 1

            if self.noinput == 3:
                inputData = "user left the chat, say a flirtatious goodbye"
            else:
                inputData = "Ask User to Repeat the Command, as No Input Detected"
        else:
            self.noinput = 0  # reset when valid input comes

        try:
            print(f"Received User Input: {inputData}")

            System = Pre_Executor(agent=self.agent, input=inputData)
            currunt_screen = get_current_screen()

            prompt = f"Currunt Screen: {currunt_screen} \n User: {inputData} \n System:{System}"

            response = chat_prompt_gen(agent=self.agent, input=prompt)

            print(response["TTS"])
            self.tts.play(response["TTS"])

            if self.noinput == 3:
                System = {"terminate": True}
            return {
                "response": response,
                "System": System
            }
        except Exception as e:
            print(f"Error in processing input: {e}")
            return {
                "response": {
                    "TTS": "Sorry, I encountered an error while processing your request."
                },
                "System": {}
            }

    def execute(self, command):
        "Executes the Command Generated by the Model, and Handles Errors if Occured"
        if not command:
            return {
                "Status": "Failed",
                "response": "No command provided"
            }
        response = Command_Executer(Command=command)
        HISTORY_CONTAINER.append({"Shell Status:" : response["Status"], "Shell Response": response["Response"]})
        if response["Status"] == "Failed":
            error_info = f"Command: {command} \n Error_Found: {response.get('Error_Found', 'No error info')}"
            debug_response = error_handler(agent=self.agent, err=error_info, STT=self.stt, TTS=self.tts)
            return debug_response
        return response
    
    def run(self):
        "Runs the Application"
        self.tts.start()
        self.stt.start()
        while True:
            input_data = self.stt.listen()
            response = self.responsed(input_data)
            print(f"Generated Response: {response}")  # Debug statement to check response
            command = response.get("response", {}).get("CMND", "NONE")
            if command != "NONE":
                shell = self.execute(command)
                response = self.responsed(f"System: Execution Completed \n Result: {shell}")
            if response.get("System", {}).get("terminate", False):
                break
        save_history()

    def stop(self):
        "Stops the Application"
        self.tts.stop()
        self.stt.stop()
        self.agent = None
        return

    
if __name__ == "__main__":
    sabrina = Sabrina()
    sabrina.run()
    sabrina.stop()