from llama_cpp import Llama
from helpers import save_history, HISTORY_CONTAINER, get_current_screen
from Core import chat_prompt_gen, system_promp_gen, Command_Executer, error_handler
from Tools import Pre_Executor
from STT import STT
from TTS import TTS
from pathlib import Path


class Sabrina:
    "Core Programme To Run The Application"
    def __init__(self):
        self.location = str(Path.cwd())       
        self.agent = Llama(
            model_path= self.location + '/models/Qwen/qwen2.5-coder-3b-instruct-q4_k_m.gguf',
            n_ctx=8192,
            n_threads=4,
            n_gpu_layers=28,
            temperature=0.1,
            verbose=False
        )
        self.tts = TTS()
        self.stt = STT()
    
    def responsed(self, inputData):
        "Creates Response for the User Input"
        if not inputData:
            raise ValueError("No input provided")
        try:
            print(f"User Input: {inputData}")
            System = Pre_Executor(agent=self.agent, input=inputData)
            currunt_screen = get_current_screen()
            prompt = f"Currunt Screen: {currunt_screen} \n User: {inputData} \n {System.get('System', '')}"
            print(f"Generated Prompt: {prompt}")
            response = chat_prompt_gen(agent=self.agent, input=prompt)
            print(f"Generated Response: {response}")
            return {
                "response": response,
                "System": System
            }
        except Exception as e:
            print(f"Error in processing input: {e}")
            return {
                "response": {
                    "TTS": "Sorry, I encountered an error while processing your request."
                },
                "System": {}
            }
    
    def execute(self, command, Sudo):
        "Executes the Command Generated by the Model, and Handles Errors if Occured"
        if not command:
            return {
                "Status": "Failed",
                "response": "No command provided"
            }
        response = Command_Executer(command = command, Dangerous= Sudo)
        HISTORY_CONTAINER.append({"Shell:", response})
        if response["Status"] == "Failed":
            error_info = f"Command: {command} \n Error_Found: {response.get('Error_Found', 'No error info')}"
            debug_response = error_handler(agent=self.agent, err=error_info, STT=self.stt, TTS=self.tts)
            return debug_response
        return response
    
    def run(self):
        "Runs the Application"
        while True:
            self.tts.start()
            input_data = self.stt.listen()
            response = self.responsed(input_data)
            print(f"Response: {response['response']['TTS']}")
            self.tts.play(response["response"]["TTS"])
            command = response["response"]["CMND"]
            if command != "NONE":
                self.execute(command, Sudo=False)
            else:
                self.tts.play(response["response"]["TTS"])
            save_history()
            if response["System"]["terminatesession"] == True:
                break

    def stop(self):
        "Stops the Application"
        self.tts.stop()
        self.stt.stop()
        self.agent = None
        return

    
if __name__ == "__main__":
    sabrina = Sabrina()
    sabrina.run()
    sabrina.stop()