from llama_cpp import Llama
from helpers import save_history, HISTORY_CONTAINER, get_current_screen
from Core import chat_prompt_gen, system_promp_gen, Command_Executer, error_handler
from Tools import prompt_Analyzer
from STT import STT
from TTS import TTS
from pathlib import Path




class Sabrina:
    "Core Programme To Run The Application"
    def __init__(self):
        self.location = str(Path.cwd())       
        self.agent = Llama(
            model_path= self.location + '/models/Qwen/qwen2.5-coder-3b-instruct-q4_k_m.gguf',
            n_ctx=8192,
            n_threads=4,
            n_gpu_layers=28,
            temperature=0.1,
            verbose=False
        )
        self.tts = TTS()
        self.stt = STT()
    
    def responsed(self, inputData):
        "Creates Response for the User Input"
        if not inputData:
            raise ValueError("No input provided")
        try:
            System = prompt_Analyzer(agent=self.agent, input=inputData)
            currunt_screen = get_current_screen()
            prompt = f"Currunt Screen: {currunt_screen} \n User: {inputData} \n {System.get('System', '')}"
            response = chat_prompt_gen(agent=self.agent, input=prompt)
            return {
                "response": response,
                "System": System
            }
        except Exception as e:
            print(f"Error in processing input: {e}")
            return {
                "response": {
                    "TTS": "Sorry, I encountered an error while processing your request."
                },
                "System": {}
            }
    
    def execute(self, command, Sudo):
        "Executes the Command Generated by the Model, and Handles Errors if Occured"
        if not command:
            return {
                "Status": "Failed",
                "response": "No command provided"
            }
        response = Command_Executer(command = command, Dangerous= Sudo)
        HISTORY_CONTAINER.append({"Shell:", response})
        if response["Status"] == "Failed":
            error_info = f"Command: {command} \n Error_Found: {response.get('Error_Found', 'No error info')}"
            debug_response = error_handler(agent=self.agent, err=error_info, STT=self.stt, TTS=self.tts)
            return debug_response
        return response
    


    
